await import("./test-auth.js");
await import("./test-platform-routes.js");
await import("./test-account-uid.js");
await import("./test-game-catalog.js");
await import("./test-casino-wallet.js");
await import("./test-crypto-derivation.js");
await import("./test-crypto-watcher.js");
await import("./test-payments.js");
await import("./test-provably-fair.js");
await import("./test-hilo-odds.js");
await import("./test-baccarat-payout.js");
await import("./test-baccarat-rules.js");
await import("./test-blackjack-payout.js");
await import("./test-keno-payout.js");
await import("./test-mines-payout.js");
await import("./test-slide-payout.js");
await import("./test-crash-payout.js");
await import("./test-plinko-payout.js");
await import("./test-sportsbook-provider.js");
await import("./test-scheduler-budget.js");
await import("./test-odds-change-detection.js");
await import("./test-bet-settlement.js");

process.exit(0);
